### ISSUE TITLE
Performance issue on green screen segmented Image

### ISSUE THREAD

**Issue by kashyappiyush1998** [hkchengrex/CascadePSP#25]
[
![PIL_Image](https://user-images.githubusercontent.com/35548940/94301227-d5271e80-ff87-11ea-814c-4c69a0265eed.png)
](url)

[
![PIL_final_edge_refined_image](https://user-images.githubusercontent.com/35548940/94301273-ea03b200-ff87-11ea-8e81-b97341f00357.png)
](url)

I wanted to make these green edges go away, by refinement. Is this possible by CascadePSP? I used the code given for testing as it is keeping the value of L=900. Is something else needed?

**Comment by hkchengrex** [comment]
What is your input mask? Which one is the output?
It might even be easier if the entire background is green, that way the algorithm can model the background. A class-agnostic algorithm might have difficulty separating FG/BG otherwise.

**Comment by kashyappiyush1998** [comment]
The first one is input and the second one is output. I want to make a pipeline with finer edges via CascadePSP at the final step.
I cannot always know that background will be monotonous. I am using Unet for background removal and then CascadePSP for better edges

**Comment by hkchengrex** [comment]
For background removal, do your UNet output a mask or an image?

**Comment by kashyappiyush1998** [comment]
It outputs the mask  image which I using PIL extract the output image

**Comment by hkchengrex** [comment]
If I understand correctly, 1. (input image) -> UNet -> initial mask 2. (input image + initial mask) -> CascadePSP -> final mask. It is better to look at the (input image + initial mask) for diagnosis. Can I take a look at them?

**Comment by kashyappiyush1998** [comment]
Sorry for being late,
Input Image is : 
![green_screen_images](https://user-images.githubusercontent.com/35548940/95247110-1397c580-0833-11eb-877b-70fe435df663.jpg)

Mask produced by U2Net is: 
![PIL_mask](https://user-images.githubusercontent.com/35548940/95247232-39bd6580-0833-11eb-867a-4ff09c3f8311.png)

Image produced by U2Net is: 
![PIL_Image](https://user-images.githubusercontent.com/35548940/95247418-75582f80-0833-11eb-9992-f51430c30059.png)

Improved mask using CascadePSP is: 
![PIL_mask_improved](https://user-images.githubusercontent.com/35548940/95247295-522d8000-0833-11eb-9d52-d44fca6ff98c.png)

Final Image using PSPCascade is: 
![PIL_final_edge_refined_image](https://user-images.githubusercontent.com/35548940/95247363-670a1380-0833-11eb-8777-68dd3fe6c395.png)

**Comment by hkchengrex** [comment]
Thanks for the images! I got a slightly different result than you:
Initial masked:
![im_mask](https://user-images.githubusercontent.com/7107196/95284405-b599cb00-0890-11eb-90d1-c77e94ec5940.png)

Refined:
![im_out](https://user-images.githubusercontent.com/7107196/95284408-b894bb80-0890-11eb-9124-6f0adb8c28db.png)

It is not perfect -- there is still a green boundary around the image. This is perhaps because it is an out-of-distribution image (we train only on natural images). Another reason is from JPEG compression artifact. If you zoom in closely, there is a darker green boundary near the portrait which our algorithm might mistake it as the actual edge. Refinement might still be of use -- in the original composited image, the green boundary is not consistent (over-segmented on the left shoulder, under-segmented on the right side of the neck) while in the refined image I think the mask consistently over-segments by 1.5 (or 2?) pixel.

Applying a erosion of (5, 5)
```
output = cv2.erode(output, kernel=np.ones((5, 5)))
```
makes the result look almost perfect to my eyes.

![im_out](https://user-images.githubusercontent.com/7107196/95285087-8b490d00-0892-11eb-92b7-3948e4139c09.png)

I also tried to play around with your initial mask (dilate/erode it by 10 or even 20 pixels), our algorithm output a similar mask given the perturbation so it might be robust enough for your application.

Thanks for your interest! I actually learnt something :)

Code for reference:
```python
import cv2
import time
import matplotlib.pyplot as plt
import segmentation_refinement as refine
import numpy as np

image = cv2.imread('im.jpg')
mask = cv2.imread('mask.png', cv2.IMREAD_GRAYSCALE)

refiner = refine.Refiner(device='cuda:0') # device can also be 'cpu'
output = refiner.refine(image, mask, fast=False, L=900) 

output = cv2.erode(output, kernel=np.ones((5, 5)))

cv2.imwrite('test/out.png', output)

mask = mask.astype(np.float32)/255
output = output.astype(np.float32)/255

cv2.imwrite('im_mask.png', image*mask[:,:,None])
cv2.imwrite('im_out.png', image*output[:,:,None])
```

**Comment by kashyappiyush1998** [comment]
Thank you So much. This will be of great use.

**Comment by kashyappiyush1998** [comment]
But I have to implement this as a general model, erosion, and dilation may work for green/blue screen images, but if I keep this for every image, this will decrease the quality of output of images with non-green screen images or image with better results by hair matting.

**Comment by hkchengrex** [comment]
Well the question was about green screen images and the problems that I have pointed out are all about green screen images. I don't observe the same issue in real-world images to start with. I think you can use it directly without erosion for real-world images. It probably wouldn't work for matting though.

**Comment by kashyappiyush1998** [comment]
Ok, Got It. Thanks
