### ISSUE TITLE
How to train the global step and local step respectively?

### ISSUE THREAD

**Issue by GOZGOXGOYGO** [hkchengrex/CascadePSP#27]
Hi,

your work is really impressive. However, I don't seem to see how the global step and local step are trained respectively. Could you please help me figure out this problem? Thank you so much!

Best,
Frank

**Comment by hkchengrex** [comment]
**Only one** refinement module is trained. It is then used in the global/local step. They are not trained separately.

**Comment by GOZGOXGOYGO** [comment]
Thanks a lot, I get it. If I train the network on very high resolution images, could you please tell me what do I need to do to modified the onlinetransformdataset? Do I still need to use random crop 224x224?

**Comment by hkchengrex** [comment]
I haven't tried that but I suspect that you would need something more complicated. 
At least you would need to use `RandomResizedCrop` instead of `RandomCrop` to get global context sometimes. That might lead to an overwhelming amount of useless crops (all foreground/background) and they should be discarded. 
Moreover, when you do have high-res training data, one suggestion is to actually train the two steps separately -- one using downsampled large crops for the global step, and the other using small crops for the local step. This is not implemented in the current repo but might worth a try.

**Comment by GOZGOXGOYGO** [comment]
I see. I notice that the test dataset named "BIG_PSPNet_SS" you provided is large enough. Could I know how did you train the two steps on this dataset?

**Comment by hkchengrex** [comment]
We did not train the model on this dataset. It is too small and is for testing purposes only.

**Comment by GOZGOXGOYGO** [comment]
So, if I want to train on this dataset. I need to firstly generate the input data for global step. And use the output of global step to continuely generate input data for local step. Is that right?

**Comment by hkchengrex** [comment]
That's one way.
Another way is to generate the inputs for the global/local steps separately and independently by perturbing the ground-truth.

**Comment by GOZGOXGOYGO** [comment]
May I ask whether using the groundtruth-based perturbation results as "seg" or using the network-based prediction results as "seg" is better for training the two step? Have you compared these two situations?

**Comment by hkchengrex** [comment]
For our case (training two steps as a single module), it is better to use perturbation because we can generate much more training pairs with variations. I would suspect that it will also be better to use ground-truth perturbation even when you train them separately.
