### ISSUE TITLE
ResNet modifications

### ISSUE THREAD

**Issue by shkarupa-alex** [hkchengrex/CascadePSP#32]
Could you please clarify what modifications are made in ResNet50 backbone and why?

Usually ResNet50 output stride is 32, but in your version it is 8 (due to dilations in last layers i think).
Also i noticed that layer3 in your code will generate 23 blocks instead of default 6

**Comment by hkchengrex** [comment]
We take the PSPNet code from [here](https://github.com/Lextal/pspnet-pytorch).

1. Output stride - using dilation is a common practice in segmentation networks to increase the output resolution
2. I think it generates 6 blocks? We call `model = ResNet(Bottleneck, [3, 4, 6, 3])` [here](https://github.com/hkchengrex/CascadePSP/blob/34794158eb22ea55c5395e7cee35378a0d91b978/models/psp/extractors.py#L169)
3. We append zero-initialized channels to the first conv layer so that it accepts the segmentation inputs.
